{% set name = "obsplus" %}
{% set version = "0.2.2" %}
{% set sha256 = "47bf1b7d912909ec9f9563fb94c334365af81a94f12123c9c56b899209449ade" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - pip
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.13.0
    - obspy >=1.2.1
    - pandas >=1.0
    - progressbar2
    - scipy
    - setuptools
    - pytables
    - pydantic >=1.8.2
    - typing_extensions

test:
  imports:
    - obsplus

about:
  home: https://github.com/niosh-mining/obsplus
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An Pandas-Centric ObsPy Expansion Pack
  description: |
    ObsPlus is a utility package for ObsPy.
  doc_url: https://github.com/niosh-mining/obsplus
  dev_url: https://github.com/niosh-mining/obsplus

extra:
  recipe-maintainers:
    - d-chambers
