{% set name = "obsplus" %}
{% set version = "0.2.5" %}
{% set sha256 = "b6a6c6ce552aca9597ba5666cf9649aec2eede6264c7bcc4febafda2f274a6d5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -v
  number: 1

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.8
    - numpy >=1.13.0
    - obspy >=1.2.1
    - pandas >=1.0
    - progressbar2
    - scipy
    - setuptools
    - pydantic >=1.9.0,<2.0.0
    - pytables
    - typing_extensions
    - packaging

test:
  imports:
    - obsplus
  commands:
    - pip check
    - python -c "import obsplus; ver = obsplus.__version__; assert ver != '0.0.0'"
  requires:
    - pip

about:
  home: https://github.com/niosh-mining/obsplus
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: An Pandas-Centric ObsPy Expansion Pack
  description: |
    ObsPlus is a utility package for ObsPy.
  doc_url: https://github.com/niosh-mining/obsplus
  dev_url: https://github.com/niosh-mining/obsplus

extra:
  recipe-maintainers:
    - d-chambers
